# Формат: название_интерфейса = socks5://user:pass@host:port
# Каждая строка — отдельный интерфейс

tun10 = socks5://wqdathyk:wc1068jclf77@104.253.112.30:6308
# tun11 = socks5://user2:pass2@host2:port2