TOKEN     = An_Sx6HQ9HDi3KaFqcDI8LqjeRdzQx2dFnEaKexxuZsYL18gYwb4ypb7df6OGEL6hSoW6ds1Hp8goiNffKg3H-7yM-3WDwG4jizbN7iSfDvPRhSZFsreEFS-ps5CVYmKlh79oKjQ2Ci-hOKry-8LuNrZ285MzuhX13l0jJKwQpYvivLq80KnHYMTXHnWSZAOejt904h1AMjsu-qVbaJLUMX5vLjwO4ouRUWpjkRLuLi8LYU3ngnYixPhJ_42g4z9or6EFM6uHvoJWgeOv_31jDPYwmGmevqBGIL3-v-_QGjCYqbZtDwVFHRBCdBvCmVf6x6eQDvdk6_ZHLb4vuO7LJS5TqPhsjIOS18jLVhXzJzbetr9rgQIOKeVYkzLAQeGYiSw1ueGHVtCGMJP8Hof3VTlC2QO8rhPiqu3867Xk0gdtnfZ023ozAh-F90vmZXqaWFw287VKrXpcgC5nK0sMn7DoBf6W_H-ewjQoF6rsCoJC3snaZzA6MbzKSf4cf9nm5y1Sls-vMXdRHp91MKWwbIPeUXImX_-rxTPxV3lulkFMUXTOQaHfj_yIgCxNJVxLDERXMPKAZiowyNRTbHeuenJDXVDBlwdvBB-CX2-4gkAXhuaEuH9j1XG0kSx6H0coIy8_xTXKnqgm2lLSnHNy6EVL8zdcH9aB4Uwz3VL076CpXmvkLof5UiMDNh4CnQnlC_BcnU
VIEWER_ID = 240876353
DEVICE_ID = e73a0f20-5cb8-47bb-8067-bde146938a58
TOKEN_2     = An_Sx6HQ9HDiL4afFnI2wsy_xKCE_iM6nc3OHWwgrJbu9AmESLLPaOszTCQORo-NiHowP6brBxlsZJPP3hJXwVYrhqoW2eC3oi3FP5YFj0K0RTAyiDEeV47G8J4YlLO9gboFI-i04ODnguemexhUopWVZfk2hnMJDJJ5hWguGT_jG0BiEIukVXtUF33HeLJGTC_Bjz8sEDu0FqomBqq9KOEGyGDP2CVU22KrHAen6i-wdQu7FSppDWq4CAL7nGSZ988VqLSKiVCM4-D5p0AvvbucNSmccO3IWPdJZAstsgl9av1GTEgUMBhqYvM8ChBNL2lAY1Da-nq1o923q1zMJYJ8J3rjKM9kf9o-HNDlG7X8otSzQlyoz_3-HGiNEAwSka7Y1DnlDtF1dnF9-4EkOIHVHov0m7lBieolQWQvdWty27Kjf9DMw1jln0FQ2zYZQq7W4o0jfrVe1Eq_BzqKcI3WWyO6a8fLdCH1nvNFEKXhz2oW0RvWBQTRMGA_FSxzYhUQGCy7j-IaAuEIZHoNwyF-v7BQucvvxEb08lJxHvUzjupbMyhkq90efKTc7VeK5RTOg5aR9IlGCtvM4o8bH7yKsmfX5tC4E7phheds4h-Dn5Te5khwQiO9W7zEJKQy_7HqJFBcY1rsCOX3Rg77r1JeMAy7Imj8A8AOWCD0O830F4FEqWaEUzATuv2cOee98ykgtIE
VIEWER_ID_2 = 240002558
DEVICE_ID_2 = 78278e74-d350-4de0-95b2-391cec33f6bb

# ─── TUN-интерфейс сервера ──────────────────────────────────────
# Используем tun1 чтобы не конфликтовать с клиентом (tun0)
TUN_NAME  = tun1
TUN_ADDR  = 10.0.1.2
TUN_PEER  = 10.0.1.1
TUN_MTU   = 1400

# ─── Батчинг ───────────────────────────────────────────────────
BATCH_WINDOW_MS     = 1000
BATCH_MAX_KB        = 4096

# ─── Прочее ────────────────────────────────────────────────────
UPLOAD_MIN_INTERVAL = 1.5
